modLoader = "javafml"
loaderVersion = "[42,)"
license = "MIT"
issueTrackerURL = "https://github.com/samedifferent/Ecologics/issues"

[[mods]]
modId = "ecologics"
version = "${version}"
displayName = "Ecologics"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ecologics"
logoFile = "icon.png"
authors = "SameButDifferent, Zero_DSRS_VX, Drigonis, Crispytwig, Irishjevil, Foquito Azul"
description = '''
Simple vanilla biome updates, with fun mobs, blocks, and more!
'''

[[dependencies.ecologics]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ecologics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,1.20)"
ordering = "NONE"
side = "BOTH"